---
latitude: 41.90655
longitude: -87.67285
map_zoom: 12
name: Wicker Park Inn
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 1329 N Wicker Park Ave
  street2: ''
  state: Illinois
  city: Chicago
  country: United States
  zip_code: '60622'
_hotel_id: WIC622
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
